# Generated by Django 5.2.12 on 2026-03-31 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitores', to='curriculum.turma')),
                ('usuario', models.OneToOneField(limit_choices_to={'perfil': 'monitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupo', 'Grupo')], max_length=20)),
                ('data_hora', models.DateTimeField()),
                ('duracao_min', models.PositiveIntegerField()),
                ('topico', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='atendimentos.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='curriculum.disciplina')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='atendimentos.monitor')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='atendimentos.monitor'),
        ),
        migrations.CreateModel(
            name='TutoriaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_participantes', models.PositiveIntegerField()),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutoria_grupo', to='atendimentos.atendimento')),
            ],
            options={
                'ordering': ['atendimento__data_hora'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='aluno',
            unique_together={('monitor', 'matricula')},
        ),
    ]
