# Generated by Django 5.2.12 on 2026-04-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriagrupo',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='tutorias_grupo', to='atendimentos.aluno'),
        ),
    ]
