# Generated by Django 5.2.12 on 2026-04-14 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_add_alunos_tutoria_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'perfil': 'monitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitores', to=settings.AUTH_USER_MODEL),
        ),
    ]
