# Generated by Django 5.2.12 on 2026-07-19 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0008_carregar_alunos_iniciais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoSAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante', models.CharField(max_length=255, verbose_name='Nome do Estudante')),
                ('categoria', models.CharField(choices=[('INFO_GERAIS', '1. Informações gerais'), ('PEDAGOGIA', '2. Pedagogia'), ('MED_DISCIPLINAR', '3. Mediação disciplinar'), ('PSIC_ESCOLAR', '4. Psicologia Escolar'), ('ENCAM_EXTERNO', '5. Encaminhamentos a instituições externas'), ('SERV_SOCIAL', '6. Serviço social'), ('NAPNEE', '7. NAPNEE'), ('SAUDE', '8. Enfermidades, tratamentos ou afastamentos médicos.')], max_length=30, verbose_name='Categoria')),
                ('registro', models.TextField(verbose_name='Registro do Atendimento (Texto Simples)')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Registro')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_sae', to=settings.AUTH_USER_MODEL, verbose_name='Profissional do SAE')),
            ],
            options={
                'verbose_name': 'Atendimento SAE',
                'verbose_name_plural': 'Atendimentos SAE',
                'ordering': ['-data_hora'],
            },
        ),
    ]
