# Generated by Django 5.2.12 on 2026-07-07 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0008_carregar_alunos_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('local', models.CharField(max_length=200)),
                ('objetivo', models.TextField()),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='em_andamento', max_length=20)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='atendimentos.monitor')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_sessao', to='atendimentos.aluno')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='atendimentos.sessaomonitoria')),
            ],
            options={
                'ordering': ['registrado_em'],
                'unique_together': {('sessao', 'matricula')},
            },
        ),
    ]
