# Generated by Django 5.2.12 on 2026-07-07 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_sessaomonitoria_participantesessao'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePreparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('duracao_min', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=300)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_preparacao', to='atendimentos.monitor')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PlanoSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('planejamento', models.TextField()),
                ('professor', models.ForeignKey(limit_choices_to={'perfil': 'professor'}, on_delete=django.db.models.deletion.PROTECT, related_name='planos_semana', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_semana', to='curriculum.turma')),
            ],
            options={
                'ordering': ['-semana_inicio'],
                'unique_together': {('turma', 'semana_inicio')},
            },
        ),
    ]
