# Generated by Django 5.2.12 on 2026-07-29 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_atendimentosae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentosae',
            name='eh_ata',
            field=models.BooleanField(default=False, verbose_name='Corresponde a uma ata?'),
        ),
        migrations.AddField(
            model_name='atendimentosae',
            name='link_ata',
            field=models.URLField(blank=True, null=True, verbose_name='Link da ata (caso seja sim)'),
        ),
        migrations.AddField(
            model_name='atendimentosae',
            name='turma_opcional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Turma (opcional)'),
        ),
        migrations.AlterField(
            model_name='atendimentosae',
            name='categoria',
            field=models.CharField(choices=[('informacoes_gerais', 'Informações gerais'), ('pedagogia', 'Pedagogia'), ('mediacao_disciplinar', 'Mediação disciplinar'), ('psicologia_escolar', 'Psicologia Escolar'), ('encaminhamentos_externos', 'Encaminhamentos a instituições externas'), ('servico_social', 'Serviço social'), ('napnee', 'NAPNEE'), ('enfermidades_afastamentos', 'Enfermidades, tratamentos ou afastamentos médicos')], max_length=50, verbose_name='Tipo de Registro'),
        ),
        migrations.AlterField(
            model_name='atendimentosae',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do registro'),
        ),
        migrations.AlterField(
            model_name='atendimentosae',
            name='estudante',
            field=models.CharField(max_length=255, verbose_name='Nome/RA/Turma'),
        ),
        migrations.AlterField(
            model_name='atendimentosae',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo registro'),
        ),
        migrations.AlterField(
            model_name='atendimentosae',
            name='registro',
            field=models.TextField(verbose_name='Registro'),
        ),
    ]
