# Generated by Django 5.2.12 on 2026-07-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0010_atendimentosae_eh_ata_atendimentosae_link_ata_and_more'),
        ('atendimentos', '0010_atividadepreparacao_planosemana'),
    ]

    operations = [
    ]
