# Generated by Django 5.2.12 on 2026-07-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_deve_trocar_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(blank=True, choices=[('monitor', 'Monitor'), ('professor', 'Professor'), ('admin', 'Admin'), ('sae', 'Profissional SAE')], max_length=20, null=True),
        ),
    ]
