# Generated by Django 5.2.12 on 2026-03-31 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['curso', 'codigo'],
                'unique_together': {('codigo', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='curriculum.disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'perfil': 'professor'}, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_como_professor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['semestre'],
                'unique_together': {('disciplina', 'semestre')},
            },
        ),
    ]
